
   function insert_gallery() {
       var images = ['http://skimage.org/docs/dev/_images/plot_holes_and_peaks.png', 'http://skimage.org/docs/dev/_images/plot_label.png', 'http://skimage.org/docs/dev/_images/plot_contours.png', 'http://skimage.org/docs/dev/_images/plot_regionprops.png', 'http://skimage.org/docs/dev/_images/plot_equalize.png', 'http://skimage.org/docs/dev/_images/plot_local_binary_pattern.png', 'http://skimage.org/docs/dev/_images/plot_convex_hull.png', 'http://skimage.org/docs/dev/_images/plot_otsu.png', 'http://skimage.org/docs/dev/_images/plot_radon_transform.png', 'http://skimage.org/docs/dev/_images/plot_canny.png', 'http://skimage.org/docs/dev/_images/plot_pyramid.png', 'http://skimage.org/docs/dev/_images/plot_gabors_from_lena.png', 'http://skimage.org/docs/dev/_images/plot_template.png', 'http://skimage.org/docs/dev/_images/plot_ssim.png', 'http://skimage.org/docs/dev/_images/plot_polygon.png', 'http://skimage.org/docs/dev/_images/plot_shapes.png', 'http://skimage.org/docs/dev/_images/plot_lena_tv_denoise.png', 'http://skimage.org/docs/dev/_images/plot_view_as_blocks.png', 'http://skimage.org/docs/dev/_images/plot_swirl.png', 'http://skimage.org/docs/dev/_images/plot_piecewise_affine.png', 'http://skimage.org/docs/dev/_images/plot_peak_local_max.png', 'http://skimage.org/docs/dev/_images/plot_segmentations.png', 'http://skimage.org/docs/dev/_images/plot_medial_transform.png', 'http://skimage.org/docs/dev/_images/plot_threshold_adaptive.png', 'http://skimage.org/docs/dev/_images/plot_hog.png', 'http://skimage.org/docs/dev/_images/plot_glcm.png', 'http://skimage.org/docs/dev/_images/plot_watershed.png', 'http://skimage.org/docs/dev/_images/plot_hough_transform.png', 'http://skimage.org/docs/dev/_images/plot_random_walker_segmentation.png', 'http://skimage.org/docs/dev/_images/plot_harris.png', 'http://skimage.org/docs/dev/_images/plot_regional_maxima.png', 'http://skimage.org/docs/dev/_images/plot_skeleton.png'];
       var links = ['http://skimage.org/docs/dev/auto_examples/plot_holes_and_peaks.html', 'http://skimage.org/docs/dev/auto_examples/plot_label.html', 'http://skimage.org/docs/dev/auto_examples/plot_contours.html', 'http://skimage.org/docs/dev/auto_examples/plot_regionprops.html', 'http://skimage.org/docs/dev/auto_examples/plot_equalize.html', 'http://skimage.org/docs/dev/auto_examples/plot_local_binary_pattern.html', 'http://skimage.org/docs/dev/auto_examples/plot_convex_hull.html', 'http://skimage.org/docs/dev/auto_examples/plot_otsu.html', 'http://skimage.org/docs/dev/auto_examples/plot_radon_transform.html', 'http://skimage.org/docs/dev/auto_examples/plot_canny.html', 'http://skimage.org/docs/dev/auto_examples/plot_pyramid.html', 'http://skimage.org/docs/dev/auto_examples/plot_gabors_from_lena.html', 'http://skimage.org/docs/dev/auto_examples/plot_template.html', 'http://skimage.org/docs/dev/auto_examples/plot_ssim.html', 'http://skimage.org/docs/dev/auto_examples/plot_polygon.html', 'http://skimage.org/docs/dev/auto_examples/plot_shapes.html', 'http://skimage.org/docs/dev/auto_examples/plot_lena_tv_denoise.html', 'http://skimage.org/docs/dev/auto_examples/plot_view_as_blocks.html', 'http://skimage.org/docs/dev/auto_examples/plot_swirl.html', 'http://skimage.org/docs/dev/auto_examples/plot_piecewise_affine.html', 'http://skimage.org/docs/dev/auto_examples/plot_peak_local_max.html', 'http://skimage.org/docs/dev/auto_examples/plot_segmentations.html', 'http://skimage.org/docs/dev/auto_examples/plot_medial_transform.html', 'http://skimage.org/docs/dev/auto_examples/plot_threshold_adaptive.html', 'http://skimage.org/docs/dev/auto_examples/plot_hog.html', 'http://skimage.org/docs/dev/auto_examples/plot_glcm.html', 'http://skimage.org/docs/dev/auto_examples/plot_watershed.html', 'http://skimage.org/docs/dev/auto_examples/plot_hough_transform.html', 'http://skimage.org/docs/dev/auto_examples/plot_random_walker_segmentation.html', 'http://skimage.org/docs/dev/auto_examples/plot_harris.html', 'http://skimage.org/docs/dev/auto_examples/plot_regional_maxima.html', 'http://skimage.org/docs/dev/auto_examples/plot_skeleton.html'];

       ix = Math.floor(Math.random() * images.length);
       document.write(
'<div class="gallery_image">      <a href="URL"><img src="IMG"/></a></div>'.replace('IMG', images[ix]).replace('URL', links[ix])
       );

       console.log('<div class="gallery_image">      <a href="URL"><img src="IMG"/></a></div>'.replace('IMG', images[ix]).replace('URL', links[ix]));
   };

